version: "3"

services:
  postgres:
    image: postgres:13
    container_name: ads-board-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: adsboard
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  redis:
    image: redis:4-alpine
    container_name: ads-board-redis
    restart: always
    ports:
      - 16379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: "local"
  redis:
    driver: "local"
